export interface AwakeningMilestone {
  id: string;
  title: string;
  codename: string;
  description: string;
  category: 'workout' | 'streak' | 'nutrition' | 'level';
  requirement: number;
  unit: string;
  statBonus: {
    stat: 'str' | 'agi' | 'vit' | 'int' | 'per';
    amount: number;
  };
  iconName: string;
  quote: string;
}

export const AWAKENING_MILESTONES: AwakeningMilestone[] = [
  {
    id: 'marathon_hunter',
    title: 'Marathon Hunter',
    codename: 'THE WIND RUNNER',
    description: 'Accumulate a grand total of 42.0 km running distance across your training.',
    category: 'workout',
    requirement: 42,
    unit: 'km',
    statBonus: { stat: 'agi', amount: 5 },
    iconName: 'Footprints',
    quote: '"The distance between death and survival is measured in stride velocity."',
  },
  {
    id: 'iron_chest',
    title: 'Iron Chest Vanguard',
    codename: 'TITAN PRESS',
    description: 'Log 1,000 total cumulative push-ups across your daily quests.',
    category: 'workout',
    requirement: 1000,
    unit: 'reps',
    statBonus: { stat: 'str', amount: 5 },
    iconName: 'Dumbbell',
    quote: '"Your chest deflects the blows that once shattered your bones."',
  },
  {
    id: 'core_sentinel',
    title: 'Core Sentinel',
    codename: 'UNBREAKABLE SPINE',
    description: 'Log 1,000 total cumulative sit-ups in pursuit of supreme abdominal resilience.',
    category: 'workout',
    requirement: 1000,
    unit: 'reps',
    statBonus: { stat: 'vit', amount: 5 },
    iconName: 'Shield',
    quote: '"A warrior whose core does not waver will never fall in the dungeon."',
  },
  {
    id: 'colossus_pillars',
    title: 'Colossus Pillars',
    codename: 'EARTH SHAKER',
    description: 'Log 1,000 total cumulative squats, forging unyielding lower body power.',
    category: 'workout',
    requirement: 1000,
    unit: 'reps',
    statBonus: { stat: 'str', amount: 5 },
    iconName: 'Flame',
    quote: '"Stand firm as a mountain against the dungeon boss charge."',
  },
  {
    id: 'centurion_burst',
    title: 'Centurion of the Dawn',
    codename: 'FIRST CENTURY',
    description: 'Complete 100 reps of any exercise in a single training session.',
    category: 'workout',
    requirement: 100,
    unit: 'reps',
    statBonus: { stat: 'str', amount: 3 },
    iconName: 'Zap',
    quote: '"The first triple-digit barrier has fallen."',
  },
  {
    id: 'unbroken_will',
    title: 'Unbroken Will',
    codename: 'SEVEN SUNS',
    description: 'Maintain a 7-day uninterrupted Daily Quest completion streak.',
    category: 'streak',
    requirement: 7,
    unit: 'days',
    statBonus: { stat: 'vit', amount: 4 },
    iconName: 'Sparkles',
    quote: '"Discipline is doing what must be done, even when every muscle screams for rest."',
  },
  {
    id: 'monarchs_resolve',
    title: "Monarch's Resolve",
    codename: 'THIRTY MOONS',
    description: 'Maintain a 30-day uninterrupted Daily Quest completion streak.',
    category: 'streak',
    requirement: 30,
    unit: 'days',
    statBonus: { stat: 'per', amount: 6 },
    iconName: 'Crown',
    quote: '"A month of relentless execution awakens dormant monarch blood."',
  },
  {
    id: 'grand_alchemist',
    title: 'Grand Culinary Alchemist',
    codename: 'METABOLIC MASTER',
    description: 'Log and analyze 20 meals using the System Nutrition Scanner.',
    category: 'nutrition',
    requirement: 20,
    unit: 'meals',
    statBonus: { stat: 'int', amount: 5 },
    iconName: 'Utensils',
    quote: '"You understand that nutrition is biological ammunition."',
  },
  {
    id: 'hydration_sovereign',
    title: 'Sovereign of Hydration',
    codename: 'AQUEOUS ELIXIR',
    description: 'Log 15,000 ml total of water intake to maintain biological cell volume.',
    category: 'nutrition',
    requirement: 15000,
    unit: 'ml',
    statBonus: { stat: 'vit', amount: 4 },
    iconName: 'Droplet',
    quote: '"Hydration powers the cellular machinery that rebuilds muscle tissue."',
  },
  {
    id: 'shadow_ascendant',
    title: 'Shadow Ascendant',
    codename: 'BEYOND HUMAN',
    description: 'Ascend to Level 25 and reach high-tier Hunter ranking.',
    category: 'level',
    requirement: 25,
    unit: 'level',
    statBonus: { stat: 'per', amount: 5 },
    iconName: 'TrendingUp',
    quote: '"The whispers of shadows now heed your command."',
  },
  {
    id: 'shadow_monarch_title',
    title: 'The Shadow Monarch',
    codename: 'RULER OF DEATH',
    description: 'Reach Level 50 and achieve the ultimate supreme rank.',
    category: 'level',
    requirement: 50,
    unit: 'level',
    statBonus: { stat: 'str', amount: 10 },
    iconName: 'Award',
    quote: '"Arise. All of existence bends before your sovereign strength."',
  },
  {
    id: 'karmayogi_title',
    title: 'Karmayogi — Sovereign of Action',
    codename: 'DUTY WITHOUT ATTACHMENT',
    description: 'Conquer your physical duties with unshakeable discipline and zero excuses.',
    category: 'streak',
    requirement: 5,
    unit: 'days',
    statBonus: { stat: 'str', amount: 6 },
    iconName: 'Flame',
    quote: '"Karmanye Vadhikaraste Ma Phaleshu Kadachana — Act with relentless devotion, expecting no shortcuts."',
  },
  {
    id: 'mind_sovereign_title',
    title: 'Mind Conqueror (Jitendriya)',
    codename: 'ABHYASA MASTERY',
    description: 'Master your recovery and senses by maintaining balanced sleep and mental fortitude.',
    category: 'streak',
    requirement: 10,
    unit: 'days',
    statBonus: { stat: 'vit', amount: 6 },
    iconName: 'Sparkles',
    quote: '"Bandhur atmatmanas tasya yenatmaivatmana jitah — The conquered mind is the greatest ally in the universe."',
  },
  {
    id: 'arjuna_focus_title',
    title: "Arjuna's Piercing Focus",
    codename: 'THE COSMIC ARCHER',
    description: 'Complete 50 km running total or intense physical output with laser precision.',
    category: 'workout',
    requirement: 50,
    unit: 'km',
    statBonus: { stat: 'agi', amount: 7 },
    iconName: 'Zap',
    quote: '"He who controls his senses and directs his focus solely upon the target never misses."',
  },
  {
    id: 'yogeshwar_chosen_title',
    title: "Yogeshwar's Chosen",
    codename: 'SUPREME EQUANIMITY',
    description: 'Ascend to Level 20 embodying the union of fierce strength, wisdom, and inner peace.',
    category: 'level',
    requirement: 20,
    unit: 'level',
    statBonus: { stat: 'per', amount: 8 },
    iconName: 'Crown',
    quote: '"Yogah karmasu kaushalam — True yoga is supreme mastery and excellence in action."',
  },
];
