export interface IndianFoodItem {
  id: string;
  name: string;
  hindiName?: string;
  category: 'roti_bread' | 'dal_lentils' | 'curry_sabzi' | 'rice_biryani' | 'south_indian' | 'breakfast_snacks' | 'dairy_protein' | 'dessert';
  defaultPortion: string;
  calories: number;
  proteinGrams: number;
  carbsGrams: number;
  fatsGrams: number;
  fiberGrams: number;
  hunterBenefit: string;
}

export const INDIAN_FOOD_DATABASE: IndianFoodItem[] = [
  // Rotis & Breads
  {
    id: 'roti_plain',
    name: 'Plain Phulka / Roti (Whole Wheat)',
    hindiName: 'रोटी / फुल्का',
    category: 'roti_bread',
    defaultPortion: '1 medium (35g)',
    calories: 85,
    proteinGrams: 3.1,
    carbsGrams: 17.5,
    fatsGrams: 0.5,
    fiberGrams: 2.5,
    hunterBenefit: 'Complex carbohydrate staple providing sustained glycogen release for long training bouts.',
  },
  {
    id: 'roti_ghee',
    name: 'Roti with Desi Ghee',
    hindiName: 'घी वाली रोटी',
    category: 'roti_bread',
    defaultPortion: '1 medium with 1 tsp ghee',
    calories: 125,
    proteinGrams: 3.1,
    carbsGrams: 17.5,
    fatsGrams: 5.0,
    fiberGrams: 2.5,
    hunterBenefit: 'Healthy butyric acid and fat-soluble vitamins from cow ghee support joint lubrication.',
  },
  {
    id: 'paratha_plain',
    name: 'Plain Tawa Paratha',
    hindiName: 'सादा पराठा',
    category: 'roti_bread',
    defaultPortion: '1 medium (60g)',
    calories: 180,
    proteinGrams: 4.2,
    carbsGrams: 26.0,
    fatsGrams: 7.2,
    fiberGrams: 3.0,
    hunterBenefit: 'Pre-workout carb loading for intensive endurance workouts.',
  },
  {
    id: 'paratha_aloo',
    name: 'Aloo Paratha (Potato Stuffed)',
    hindiName: 'आलू पराठा',
    category: 'roti_bread',
    defaultPortion: '1 medium (120g)',
    calories: 260,
    proteinGrams: 5.8,
    carbsGrams: 42.0,
    fatsGrams: 8.5,
    fiberGrams: 4.2,
    hunterBenefit: 'High potassium and complex starches for post-leg-day muscle replenishment.',
  },
  {
    id: 'paratha_paneer',
    name: 'Paneer Paratha (High-Protein)',
    hindiName: 'पनीर पराठा',
    category: 'roti_bread',
    defaultPortion: '1 medium (130g)',
    calories: 320,
    proteinGrams: 14.5,
    carbsGrams: 34.0,
    fatsGrams: 14.0,
    fiberGrams: 3.8,
    hunterBenefit: 'S-Rank muscle builder combining casein protein with whole wheat carbohydrates.',
  },
  {
    id: 'paratha_gobi',
    name: 'Gobi / Cauliflower Paratha',
    hindiName: 'गोभी पराठा',
    category: 'roti_bread',
    defaultPortion: '1 medium (110g)',
    calories: 210,
    proteinGrams: 5.0,
    carbsGrams: 32.0,
    fatsGrams: 7.5,
    fiberGrams: 5.0,
    hunterBenefit: 'High dietary fiber and brassica antioxidants for systemic cellular recovery.',
  },

  // Dals & Lentils
  {
    id: 'dal_tadka',
    name: 'Yellow Moong / Toor Dal Tadka',
    hindiName: 'दाल तड़का',
    category: 'dal_lentils',
    defaultPortion: '1 katori / bowl (180ml)',
    calories: 155,
    proteinGrams: 8.5,
    carbsGrams: 22.0,
    fatsGrams: 4.0,
    fiberGrams: 6.0,
    hunterBenefit: 'Easily digestible plant protein infused with anti-inflammatory turmeric and cumin.',
  },
  {
    id: 'dal_makhani',
    name: 'Dal Makhani (Black Lentil & Butter)',
    hindiName: 'दाल मखनी',
    category: 'dal_lentils',
    defaultPortion: '1 katori / bowl (200ml)',
    calories: 275,
    proteinGrams: 10.5,
    carbsGrams: 28.0,
    fatsGrams: 13.5,
    fiberGrams: 7.5,
    hunterBenefit: 'Dense clean-bulk calories loaded with iron and magnesium for deep tissue restoration.',
  },
  {
    id: 'rajma_curry',
    name: 'Rajma Masala (Red Kidney Beans)',
    hindiName: 'राजमा मसाला',
    category: 'dal_lentils',
    defaultPortion: '1 medium bowl (200g)',
    calories: 220,
    proteinGrams: 12.0,
    carbsGrams: 36.0,
    fatsGrams: 4.5,
    fiberGrams: 9.0,
    hunterBenefit: 'High leucine and resistant starch aiding muscle synthesis and gut microbiome balance.',
  },
  {
    id: 'chole_masala',
    name: 'Pindi / Amritsari Chole (Chickpeas)',
    hindiName: 'छोले मसाला',
    category: 'dal_lentils',
    defaultPortion: '1 medium bowl (200g)',
    calories: 245,
    proteinGrams: 11.8,
    carbsGrams: 38.0,
    fatsGrams: 6.0,
    fiberGrams: 10.0,
    hunterBenefit: 'High zinc, iron, and slow-burning carbs preventing mid-day fatigue.',
  },
  {
    id: 'sambar_south',
    name: 'South Indian Vegetable Sambar',
    hindiName: 'सांभर',
    category: 'dal_lentils',
    defaultPortion: '1 bowl (220ml)',
    calories: 130,
    proteinGrams: 6.5,
    carbsGrams: 22.0,
    fatsGrams: 2.2,
    fiberGrams: 5.5,
    hunterBenefit: 'Electrolyte-rich broth containing drumstick, tamarind, and toor dal for rehydration.',
  },

  // Curries & Sabzis
  {
    id: 'paneer_bhurji',
    name: 'Paneer Bhurji (Scrambled Cottage Cheese)',
    hindiName: 'पनीर भुर्जी',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl (150g)',
    calories: 290,
    proteinGrams: 18.5,
    carbsGrams: 7.0,
    fatsGrams: 21.0,
    fiberGrams: 2.0,
    hunterBenefit: 'Prime vegetarian hypertrophy fuel loaded with bioavailable calcium and leucine.',
  },
  {
    id: 'paneer_tikka',
    name: 'Tandoori Paneer Tikka (Grilled)',
    hindiName: 'पनीर टिक्का',
    category: 'curry_sabzi',
    defaultPortion: '6-7 pieces (180g)',
    calories: 280,
    proteinGrams: 22.0,
    carbsGrams: 9.0,
    fatsGrams: 17.0,
    fiberGrams: 3.0,
    hunterBenefit: 'Grilled lean protein with capsicum and onion—ideal S-Rank post-workout meal.',
  },
  {
    id: 'palak_paneer',
    name: 'Palak Paneer (Spinach & Cottage Cheese)',
    hindiName: 'पालक पनीर',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl (200g)',
    calories: 260,
    proteinGrams: 14.0,
    carbsGrams: 9.0,
    fatsGrams: 19.0,
    fiberGrams: 4.5,
    hunterBenefit: 'Combines bioavailable iron from spinach with high-grade dairy protein for oxygen transport.',
  },
  {
    id: 'soya_chunks_curry',
    name: 'Soya Chunks Curry (Max Protein Vegetarian)',
    hindiName: 'सोया चंक्स करी',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl (50g dry soya equiv)',
    calories: 230,
    proteinGrams: 26.5,
    carbsGrams: 16.0,
    fatsGrams: 3.5,
    fiberGrams: 7.0,
    hunterBenefit: 'Supercharged vegetarian amino acid bomb boasting over 50% protein density by dry weight.',
  },
  {
    id: 'chicken_curry_home',
    name: 'Homestyle Chicken Curry',
    hindiName: 'चिकन करी',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl with 150g chicken',
    calories: 285,
    proteinGrams: 32.0,
    carbsGrams: 6.0,
    fatsGrams: 14.0,
    fiberGrams: 1.5,
    hunterBenefit: 'Complete animal protein containing creatine and all 9 essential amino acids.',
  },
  {
    id: 'butter_chicken',
    name: 'Butter Chicken (Murgh Makhani)',
    hindiName: 'बटर चिकन',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl with 150g chicken',
    calories: 420,
    proteinGrams: 30.0,
    carbsGrams: 14.0,
    fatsGrams: 28.0,
    fiberGrams: 2.0,
    hunterBenefit: 'Calorie-dense bulk ration rich in protein and dietary lipids.',
  },
  {
    id: 'egg_curry',
    name: 'Indian Egg Curry (2 Whole Boiled Eggs)',
    hindiName: 'अंडा करी',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl with 2 eggs',
    calories: 240,
    proteinGrams: 15.0,
    carbsGrams: 8.0,
    fatsGrams: 16.0,
    fiberGrams: 1.5,
    hunterBenefit: 'Choline for cognitive focus, plus complete albumin and yolk micro-nutrients.',
  },
  {
    id: 'fish_curry',
    name: 'Bengali / Goan Fish Curry',
    hindiName: 'मछली करी',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl (150g fish)',
    calories: 220,
    proteinGrams: 28.0,
    carbsGrams: 4.0,
    fatsGrams: 10.0,
    fiberGrams: 1.0,
    hunterBenefit: 'Omega-3 fatty acids reduce workout-induced delayed onset muscle soreness (DOMS).',
  },
  {
    id: 'bhindi_masala',
    name: 'Bhindi Masala (Okra Stir-Fry)',
    hindiName: 'भिंडी मसाला',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl (150g)',
    calories: 120,
    proteinGrams: 3.0,
    carbsGrams: 12.0,
    fatsGrams: 7.0,
    fiberGrams: 5.5,
    hunterBenefit: 'Rich in soluble fiber that regulates blood glucose spikes during carbohydrate meals.',
  },
  {
    id: 'aloo_gobi',
    name: 'Aloo Gobi Sabzi',
    hindiName: 'आलू गोभी',
    category: 'curry_sabzi',
    defaultPortion: '1 bowl (160g)',
    calories: 160,
    proteinGrams: 3.5,
    carbsGrams: 24.0,
    fatsGrams: 6.5,
    fiberGrams: 4.0,
    hunterBenefit: 'Electrolytes and vitamin C supporting collagen formation for tendon strength.',
  },

  // Rice & Biryanis
  {
    id: 'chicken_biryani',
    name: 'Hyderabadi Chicken Biryani',
    hindiName: 'चिकन बिरयानी',
    category: 'rice_biryani',
    defaultPortion: '1 full plate (350g)',
    calories: 520,
    proteinGrams: 34.0,
    carbsGrams: 62.0,
    fatsGrams: 16.0,
    fiberGrams: 3.5,
    hunterBenefit: 'Ultimate post-dungeon feast packing both high carbohydrates and lean chicken muscle fuel.',
  },
  {
    id: 'veg_biryani',
    name: 'Vegetable Dum Biryani with Paneer',
    hindiName: 'वेज बिरयानी',
    category: 'rice_biryani',
    defaultPortion: '1 full plate (350g)',
    calories: 440,
    proteinGrams: 16.0,
    carbsGrams: 68.0,
    fatsGrams: 12.0,
    fiberGrams: 5.5,
    hunterBenefit: 'Rich spice blend containing cardamom, cloves, and saffron that aids metabolic expenditure.',
  },
  {
    id: 'rice_steamed',
    name: 'Steamed White Basmati Rice',
    hindiName: 'उबले चावल',
    category: 'rice_biryani',
    defaultPortion: '1 cup cooked (150g)',
    calories: 195,
    proteinGrams: 4.0,
    carbsGrams: 44.0,
    fatsGrams: 0.5,
    fiberGrams: 1.0,
    hunterBenefit: 'Fast-digesting clean glycogen refueling without gastrointestinal burden.',
  },
  {
    id: 'khichdi_dal',
    name: 'Moong Dal Khichdi with Ghee',
    hindiName: 'मूंग दाल खिचड़ी',
    category: 'rice_biryani',
    defaultPortion: '1 large bowl (250g)',
    calories: 290,
    proteinGrams: 11.5,
    carbsGrams: 48.0,
    fatsGrams: 6.5,
    fiberGrams: 5.0,
    hunterBenefit: 'The ancient Indian Ayurvedic recovery elixir—gentle on stomach and rich in amino acids.',
  },

  // South Indian Classics
  {
    id: 'idli_sambar',
    name: 'Steamed Idli with Sambar (2 pcs)',
    hindiName: 'इडली सांभर',
    category: 'south_indian',
    defaultPortion: '2 idlis + 1 bowl sambar',
    calories: 220,
    proteinGrams: 9.0,
    carbsGrams: 42.0,
    fatsGrams: 2.0,
    fiberGrams: 5.0,
    hunterBenefit: 'Fermented batter promotes gut bioavailability and healthy microbiome assimilation.',
  },
  {
    id: 'masala_dosa',
    name: 'Crispy Masala Dosa with Chutney',
    hindiName: 'मसाला डोसा',
    category: 'south_indian',
    defaultPortion: '1 full dosa with potato filling',
    calories: 360,
    proteinGrams: 7.5,
    carbsGrams: 55.0,
    fatsGrams: 12.5,
    fiberGrams: 4.5,
    hunterBenefit: 'Satisfying energizing meal providing endurance carbohydrates for running distance.',
  },
  {
    id: 'plain_dosa',
    name: 'Plain Sada Dosa (No potato)',
    hindiName: 'सादा डोसा',
    category: 'south_indian',
    defaultPortion: '1 medium dosa',
    calories: 175,
    proteinGrams: 4.0,
    carbsGrams: 29.0,
    fatsGrams: 5.0,
    fiberGrams: 2.0,
    hunterBenefit: 'Light pre-training carbohydrate source with minimal fat content.',
  },
  {
    id: 'upma_veg',
    name: 'Rava Vegetable Upma',
    hindiName: 'उपमा',
    category: 'south_indian',
    defaultPortion: '1 bowl (180g)',
    calories: 230,
    proteinGrams: 6.0,
    carbsGrams: 36.0,
    fatsGrams: 7.0,
    fiberGrams: 4.0,
    hunterBenefit: 'Mustard seeds and curry leaves stimulate gastric juices and blood circulation.',
  },

  // Breakfast, Snacks & High-Protein Staples
  {
    id: 'besan_chilla',
    name: 'Besan Chilla (Gram Flour Pancake)',
    hindiName: 'बेसन चीला',
    category: 'breakfast_snacks',
    defaultPortion: '2 chillas (140g)',
    calories: 240,
    proteinGrams: 13.0,
    carbsGrams: 32.0,
    fatsGrams: 6.5,
    fiberGrams: 6.0,
    hunterBenefit: 'Low GI, gluten-free vegetarian protein pancake packed with complex B vitamins.',
  },
  {
    id: 'moong_dal_chilla',
    name: 'Moong Dal Chilla / Pesarattu',
    hindiName: 'मूंग दाल चीला',
    category: 'breakfast_snacks',
    defaultPortion: '2 chillas (140g)',
    calories: 220,
    proteinGrams: 16.0,
    carbsGrams: 30.0,
    fatsGrams: 4.5,
    fiberGrams: 7.5,
    hunterBenefit: 'Premier fitness breakfast boasting high protein, potassium, and high satiety.',
  },
  {
    id: 'sattu_drink',
    name: 'Bihari Sattu Drink / Sharbat',
    hindiName: 'सत्तू शरबत (देसी प्रोटीन)',
    category: 'breakfast_snacks',
    defaultPortion: '1 tall glass (40g sattu flour in water)',
    calories: 165,
    proteinGrams: 11.5,
    carbsGrams: 25.0,
    fatsGrams: 2.2,
    fiberGrams: 6.5,
    hunterBenefit: 'The traditional "Desi Protein Shake"—cools body core temperature and delivers stamina.',
  },
  {
    id: 'poha_peanut',
    name: 'Kanda Poha with Roasted Peanuts',
    hindiName: 'कांदा पोहा',
    category: 'breakfast_snacks',
    defaultPortion: '1 plate (180g)',
    calories: 260,
    proteinGrams: 6.5,
    carbsGrams: 44.0,
    fatsGrams: 7.5,
    fiberGrams: 3.5,
    hunterBenefit: 'Iron-flattened rice loaded with peanuts for energy density and cardiac health.',
  },
  {
    id: 'sprouts_salad',
    name: 'Moong & Kala Chana Sprouts Salad',
    hindiName: 'अंकुरित मूंग सलाद',
    category: 'breakfast_snacks',
    defaultPortion: '1 bowl (150g)',
    calories: 150,
    proteinGrams: 11.0,
    carbsGrams: 24.0,
    fatsGrams: 1.5,
    fiberGrams: 8.0,
    hunterBenefit: 'Living enzymes, chlorophyll, and micronutrients maximizing cellular repair speed.',
  },

  // Dairy & High Protein
  {
    id: 'dahi_curd',
    name: 'Fresh Cow Milk Dahi / Curd',
    hindiName: 'दही',
    category: 'dairy_protein',
    defaultPortion: '1 katori (150g)',
    calories: 95,
    proteinGrams: 5.5,
    carbsGrams: 6.5,
    fatsGrams: 5.0,
    fiberGrams: 0,
    hunterBenefit: 'Natural probiotics that bolster immunity and optimize gut nutrient absorption.',
  },
  {
    id: 'paneer_raw',
    name: 'Raw Cottage Cheese (Paneer)',
    hindiName: 'कच्चा पनीर',
    category: 'dairy_protein',
    defaultPortion: '100g raw cubes',
    calories: 265,
    proteinGrams: 18.3,
    carbsGrams: 4.2,
    fatsGrams: 20.8,
    fiberGrams: 0,
    hunterBenefit: 'Pure slow-digesting casein protein—ideal before sleep to prevent muscle breakdown.',
  },
  {
    id: 'lassi_sweet',
    name: 'Traditional Sweet Lassi',
    hindiName: 'मीठी लस्सी',
    category: 'dairy_protein',
    defaultPortion: '1 glass (250ml)',
    calories: 220,
    proteinGrams: 6.5,
    carbsGrams: 34.0,
    fatsGrams: 7.0,
    fiberGrams: 0,
    hunterBenefit: 'Rapid glycogen refueling drink after exhaustive outdoor gate battles.',
  },
  {
    id: 'chaas_buttermilk',
    name: 'Masala Chaas / Spiced Buttermilk',
    hindiName: 'मसाला छाछ',
    category: 'dairy_protein',
    defaultPortion: '1 tall glass (300ml)',
    calories: 60,
    proteinGrams: 3.5,
    carbsGrams: 5.0,
    fatsGrams: 2.5,
    fiberGrams: 0.5,
    hunterBenefit: 'Zero-guilt electrolyte rehydration beverage seasoned with roasted jeera and mint.',
  },

  // Sweets & Treats
  {
    id: 'gulab_jamun',
    name: 'Gulab Jamun (1 piece)',
    hindiName: 'गुलाब जामुन',
    category: 'dessert',
    defaultPortion: '1 piece (50g)',
    calories: 175,
    proteinGrams: 2.5,
    carbsGrams: 28.0,
    fatsGrams: 6.5,
    fiberGrams: 0.2,
    hunterBenefit: 'Cheat day calorie burst—use right before intense high-volume training to fuel pumps.',
  },
  {
    id: 'kaju_katli',
    name: 'Kaju Katli (Cashew Fudge)',
    hindiName: 'काजू कतली',
    category: 'dessert',
    defaultPortion: '2 pieces (30g)',
    calories: 130,
    proteinGrams: 3.0,
    carbsGrams: 16.0,
    fatsGrams: 6.5,
    fiberGrams: 0.8,
    hunterBenefit: 'Cashew heart-healthy monounsaturated fats and instant glucose for peak bursts.',
  },
];

export function findIndianFoodMatches(query: string): IndianFoodItem[] {
  if (!query || query.trim().length === 0) return INDIAN_FOOD_DATABASE.slice(0, 12);
  const q = query.toLowerCase().trim();
  return INDIAN_FOOD_DATABASE.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      (item.hindiName && item.hindiName.includes(q)) ||
      item.category.toLowerCase().includes(q)
  );
}
